Update check-symlinks.yml

diff --git a/.github/workflows/check-symlinks.yml b/.github/workflows/check-symlinks.yml
--- a/.github/workflows/check-symlinks.yml
+++ b/.github/workflows/check-symlinks.yml
@@ -83,20 +83,16 @@ jobs:
           #   fi
           # done < symlink_folders.txt
 
-          while IFS= read -r folder; do
+          while IFS= read -r symlink_folder; do
+            echo "folder1: $symlink_folder"
             # Check if the folder exists and is not the root directory
-            echo "folder1: $folder"
-            if [ -d "$folder" ] && [ "$folder" != "." ]; then
-              echo "folder2: $folder"
-              # Check if the folder contains any symlink files
-              if [ -n "$(find "$folder" -maxdepth 1 -type l)" ]; then
-                echo "folder3: $folder"
-                # Check if any changed files are directly within this folder
-                if [ -n "$(git diff --name-only origin/main -- "$folder" | grep -v '/')" ]; then
-                  echo "folder4: $folder"
-                  echo "Error: New files added to symlink folder $folder"
-                  exit 1
-                fi
+            if [ -d "$symlink_folder" ] && [ "$symlink_folder" != "." ]; then
+              echo "folder2: $symlink_folder"
+              # Check if any changed files have the exact same path as the symlink-containing folder
+              if [ -n "$(git diff --name-only origin/main | grep "^$symlink_folder\$")" ]; then
+                echo "folder3: $symlink_folder"
+                echo "Error: New files added to symlink folder $symlink_folder"
+                exit 1
               fi
             fi
           done < symlink_folders.txt
