Update check-symlinks.yml

diff --git a/.github/workflows/check-symlinks.yml b/.github/workflows/check-symlinks.yml
--- a/.github/workflows/check-symlinks.yml
+++ b/.github/workflows/check-symlinks.yml
@@ -51,6 +51,31 @@ on:
     paths:
       - '**'
 
+# jobs:
+#   check_symlinks:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Checkout repository
+#         uses: actions/checkout@v2
+
+#       - name: Fetch main branch from remote
+#         run: git fetch origin main:main
+
+#       - name: Find symlinks in folders
+#         run: |
+#           find . -type l -exec dirname {} + | sort -u > symlink_folders.txt
+
+#       - name: Check for new files in symlink folders
+#         run: |
+#           while IFS= read -r folder; do
+#             if [ -n "$(git diff --name-only main $folder)" ]; then
+#               echo "Error: New files added to symlink folder $folder"
+#               exit 1
+#             fi
+#           done < symlink_folders.txt
+
+#       - name: Cleanup
+#         run: rm symlink_folders.txt
 jobs:
   check_symlinks:
     runs-on: ubuntu-latest
@@ -58,17 +83,15 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v2
 
-      - name: Fetch main branch from remote
-        run: git fetch origin main:main
-
-      - name: Find symlinks in folders
+      - name: Find folders with symlinks
         run: |
           find . -type l -exec dirname {} + | sort -u > symlink_folders.txt
+          cat symlink_folders.txt
 
       - name: Check for new files in symlink folders
         run: |
           while IFS= read -r folder; do
-            if [ -n "$(git diff --name-only main $folder)" ]; then
+            if [ -n "$(git diff --name-only HEAD^ $folder)" ]; then
               echo "Error: New files added to symlink folder $folder"
               exit 1
             fi
