Update check-symlinks.yml

diff --git a/.github/workflows/check-symlinks.yml b/.github/workflows/check-symlinks.yml
--- a/.github/workflows/check-symlinks.yml
+++ b/.github/workflows/check-symlinks.yml
@@ -73,11 +73,24 @@ jobs:
           #     exit 1
           #   fi
           # done < symlink_folders.txt
+
+          # while IFS= read -r folder; do
+          #   if [ -d "$folder" ]; then
+          #     if [ -n "$(git diff --name-only origin/main $folder)" ]; then
+          #       echo "Error: New files added to symlink folder $folder"
+          #       exit 1
+          #     fi
+          #   fi
+          # done < symlink_folders.txt
+
           while IFS= read -r folder; do
             if [ -d "$folder" ]; then
-              if [ -n "$(git diff --name-only origin/main $folder)" ]; then
-                echo "Error: New files added to symlink folder $folder"
-                exit 1
+              # Check if the folder contains any symlink files
+              if [ -n "$(find "$folder" -maxdepth 1 -type l)" ]; then
+                if [ -n "$(git diff --name-only origin/main $folder)" ]; then
+                  echo "Error: New files added to symlink folder $folder"
+                  exit 1
+                fi
               fi
             fi
           done < symlink_folders.txt
